# Generated by Django 2.2.5 on 2021-02-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20, unique=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(max_length=500, unique=True, verbose_name='내용'),
        ),
    ]
