# Generated by Django 2.2.5 on 2021-02-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopinfo',
            name='recent_update',
        ),
    ]
