# Generated by Django 2.2.5 on 2021-02-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_remove_shopinfo_recent_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='address',
            field=models.CharField(max_length=300, verbose_name='위치'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='direct_number',
            field=models.CharField(max_length=200, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='opening_hours',
            field=models.CharField(max_length=200, verbose_name='영업시간'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_name',
            field=models.CharField(max_length=200, verbose_name='가게이름'),
        ),
    ]
