# Generated by Django 2.2.5 on 2021-02-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0003_auto_20210215_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopInfo',
        ),
    ]
